/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.gr.java_conf.saka.github.actions.sandbox.list;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import org.junit.jupiter.api.Test;

public class LinkedListTest {

  @Test
  public void testGetThrowsNPW() {
    LinkedList list = new LinkedList();
    assertThrows(IndexOutOfBoundsException.class, () -> {
      @SuppressWarnings("unused")
      var ignored = list.get(0);
    });
  }

  @Test
  public void testConstructor() {
    LinkedList list = new LinkedList();
    assertEquals(0, list.size());
  }

  @Test
  public void testAdd() {
    LinkedList list = new LinkedList();

    list.add("one");
    assertEquals(1, list.size());
    assertEquals("one", list.get(0));

    list.add("two");
    assertEquals(2, list.size());
    assertEquals("two", list.get(1));
  }

  @Test
  public void testRemove() {
    LinkedList list = new LinkedList();

    list.add("one");
    list.add("two");
    list.add("three");
    assertTrue(list.remove("one"));

    assertEquals(2, list.size());
    assertEquals("two", list.get(0));
    assertEquals("three", list.get(1));

    assertTrue(list.remove("three"));
    assertEquals(1, list.size());
    assertEquals("two", list.get(0));

    assertTrue(list.remove("two"));
    assertEquals(0, list.size());
  }

  @Test
  public void testRemoveMissing() {
    LinkedList list = new LinkedList();

    list.add("one");
    list.add("two");
    assertFalse(list.remove("three"));
    assertEquals(2, list.size());
  }
}
