/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.gr.java_conf.saka.github.actions.sandbox.app;

class MessageUtils {
    public static String getMessage() {
        return "Hello      World!";
    }
}
