# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Get Date (to use as a unique ID)
        id: get-date
        run: |
          echo "::set-output name=date::$(/bin/date +%s)"
        shell: bash
      - name: Restore coverage of the target branch to report coverage changes
        uses: actions/cache@v2
        if: github.event_name == 'pull_request'
        with:
          path: |
            build/reports/jacoco/jacocoMergedReport/jacoco_summary.json
          key: no-cache-hit-jacoco-report-json-${{ steps.get-date.outputs.date }}
          restore-keys: refs/heads/${{ github.base_ref }}-jacoco-report-json

      - name: Build with Gradle
        run: ./gradlew build jacocoMergedReport

      - name: Report coverage to the PR
        uses: actions/github-script@v3
        if: github.event_name == 'pull_request'
        with:
          script: |
            const fs = require('fs')
            const report = fs.readFileSync('build/reports/jacoco/jacocoMergedReport/jacoco_summary.md')
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `${report}`
            })

      - uses: codecov/codecov-action@v1
        with:
          file: build/reports/jacoco/jacocoMergedReport/jacocoMergedReport.xml
          flags: unittests
          fail_ci_if_error: true
          verbose: true

      - name: Save coverage as a cache for next PR
        uses: actions/cache@v2
        if: github.event_name == 'push'
        with:
          path: |
            build/reports/jacoco/jacocoMergedReport/jacoco_summary.json
          key: ${{ github.ref }}-jacoco-report-json-${{ hashFiles('build/reports/jacoco/jacocoMergedReport/jacoco_summary.json') }}
